config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  begin
      ActiveAdmin.routes(self)
    rescue Exception => e
      puts "ActiveAdmin: #{e.class}: #{e}"
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"
  get 'rsvp', to: 'home#rsvp'

  authenticate :admin_user, lambda { |u| u.admin? } do
    mount Crono::Web, at: '/crono'
  end


  resources :reports do
  member do
    get :qreport
  end
  resources :people do
  member do
    get :delete
  end
end
end

end

app/models/person.rb
class Person < ApplicationRecord
  has_many :mccampaignsends
  has_many :mccampaigns, :through => :mccampaignsends
  has_many :group_memberships
  has_many :ingroups, :through => :group_memberships, :source => :group
  has_many :group_attendances
  has_many :attended, :through =>  :group_attendances, :source => :group
  has_many :household_people
  has_many :family, :through =>  :household_people, :source => :household
  has_many :peoplelist_people
  has_many :lists, :through =>  :peoplelist_people, :source => :peoplelist
  has_many :teammembers
  has_many :mailchimplists
  has_many :workflowcards
  has_many :check_ins
  has_many :donations
  has_many :geo_maps
  has_many :pledges
  has_one :campu

  serialize :email_array
  scope :active, lambda { where(:people_status => "active")}
  scope :inactive, lambda { where(:people_status => "inactive")}
  scope :sorted, lambda { order("pco_id ASC") }
  scope :newest_first, lambda { order("created_at DESC") }
  scope :campbell, -> { where(:campus => "Campbell")}
  scope :gilroy, -> { where(:campus => "Gilroy")}
  scope :morganhill, -> { where(:campus => "Morgan Hill")}
  scope :sanjose, -> { where(:campus => "San Jose")}
  scope :member, -> { where(:membership => "Member")}

  # scope :focallist, -> { joins(:lists).where("peoplelists.focallist = ?",TRUE) }
  # # Enumerize
   extend Enumerize
   enumerize :week1checkin, in: [:R, :V, :N], default: :N
   enumerize :week2checkin, in: [:R, :V, :N], default: :N
   enumerize :week3checkin, in: [:R, :V, :N], default: :N
   enumerize :week4checkin, in: [:R, :V, :N], default: :N
   enumerize :week5checkin, in: [:R, :V, :N], default: :N
   enumerize :week6checkin, in: [:R, :V, :N], default: :N
   enumerize :week7checkin, in: [:R, :V, :N], default: :N
   enumerize :week8checkin, in: [:R, :V, :N], default: :N
   enumerize :week9checkin, in: [:R, :V, :N], default: :N
   enumerize :week10checkin, in: [:R, :V, :N], default: :N
   enumerize :week11checkin, in: [:R, :V, :N], default: :N
   enumerize :week12checkin, in: [:R, :V, :N], default: :N
   enumerize :week13checkin, in: [:R, :V, :N], default: :N
   enumerize :week14checkin, in: [:R, :V, :N], default: :N
   enumerize :week15checkin, in: [:R, :V, :N], default: :N
   enumerize :week16checkin, in: [:R, :V, :N], default: :N
   enumerize :week17checkin, in: [:R, :V, :N], default: :N
   enumerize :week18checkin, in: [:R, :V, :N], default: :N
   enumerize :week1gift, in: [:D, :K, :M, :N], default: :N
   enumerize :week2gift, in: [:D, :K, :M, :N], default: :N
   enumerize :week3gift, in: [:D, :K, :M, :N], default: :N
   enumerize :week4gift, in: [:D, :K, :M, :N], default: :N
   enumerize :week5gift, in: [:D, :K, :M, :N], default: :N
   enumerize :week6gift, in: [:D, :K, :M, :N], default: :N
   enumerize :week7gift, in: [:D, :K, :M, :N], default: :N
   enumerize :week8gift, in: [:D, :K, :M, :N], default: :N
   enumerize :week9gift, in: [:D, :K, :M, :N], default: :N
   enumerize :week10gift, in: [:D, :K, :M, :N], default: :N
   enumerize :week11gift, in: [:D, :K, :M, :N], default: :N
   enumerize :week12gift, in: [:D, :K, :M, :N], default: :N
   enumerize :week13gift, in: [:D, :K, :M, :N], default: :N
   enumerize :week14gift, in: [:D, :K, :M, :N], default: :N
   enumerize :week15gift, in: [:D, :K, :M, :N], default: :N
   enumerize :week16gift, in: [:D, :K, :M, :N], default: :N
   enumerize :week17gift, in: [:D, :K, :M, :N], default: :N
   enumerize :week18gift, in: [:D, :K, :M, :N], default: :N

  #
  #  # Rails Enum
   enum status: { active: 0, archived: 1 }

    def self.search(search)
      where("last_name LIKE ? OR first_name LIKE ? OR email LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
    end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

#  layout 'admin'
    layout 'application'

    before_action :confirm_logged_in

  def index

    @people = Person.where(:people_status => "active").sorted.page(params[:page]).per(25)
    if params[:search]
        @people = Person.search(params[:search]).sorted.page(params[:page]).per(25)
      else
        @people = Person.where(:people_status => "active").sorted.page(params[:page]).per(25)
      end

  end

  def campbell

    @people = Person.campbell.where(:people_status => "active").sorted.page(params[:page]).per(25)
    if params[:search]
        @people = Person.search(params[:search]).campbell.sorted.page(params[:page]).per(25)
      else
        @people = Person.where(:people_status => "active").campbell.sorted.page(params[:page]).per(25)
      end

  end
  def gilroy

    @people = Person.gilroy.where(:people_status => "active").sorted.page(params[:page]).per(25)
    if params[:search]
        @people = Person.search(params[:search]).gilroy.sorted.page(params[:page]).per(25)
      else
        @people = Person.where(:people_status => "active").gilroy.sorted.page(params[:page]).per(25)
      end

  end
  def morganhill

    @people = Person.morganhill.where(:people_status => "active").sorted.page(params[:page]).per(25)
    if params[:search]
        @people = Person.search(params[:search]).morganhill.sorted.page(params[:page]).per(25)
      else
        @people = Person.where(:people_status => "active").morganhill.sorted.page(params[:page]).per(25)
      end

  end
  def sanjose

    @people = Person.sanjose.where(:people_status => "active").sorted.page(params[:page]).per(25)
    if params[:search]
        @people = Person.search(params[:search]).sanjose.sorted.page(params[:page]).per(25)
      else
        @people = Person.where(:people_status => "active").sanjose.sorted.page(params[:page]).per(25)
      end

  end

  def donations

    @people = Person.where(:people_status => "active").sorted.page(params[:page]).per(50)
    if params[:search]
        @people = Person.search(params[:search]).sorted.page(params[:page]).per(50)
      else
        @people = Person.where(:people_status => "active").sorted.page(params[:page]).per(50)
      end

  end
  def dcampbell

    @people = Person.campbell.where(:people_status => "active").sorted.page(params[:page]).per(50)
    if params[:search]
        @people = Person.search(params[:search]).campbell.sorted.page(params[:page]).per(50)
      else
        @people = Person.where(:people_status => "active").campbell.sorted.page(params[:page]).per(50)
      end

  end
  def dmorganhill

    @people = Person.morganhill.where(:people_status => "active").sorted.page(params[:page]).per(50)
    if params[:search]
        @people = Person.search(params[:search]).morganhill.sorted.page(params[:page]).per(50)
      else
        @people = Person.where(:people_status => "active").morganhill.sorted.page(params[:page]).per(50)
      end

  end
  def dgilroy

    @people = Person.gilroy.where(:people_status => "active").sorted.page(params[:page]).per(50)
    if params[:search]
        @people = Person.search(params[:search]).gilroy.sorted.page(params[:page]).per(50)
      else
        @people = Person.where(:people_status => "active").gilroy.sorted.page(params[:page]).per(50)
      end

  end
  def dsanjose

    @people = Person.sanjose.where(:people_status => "active").sorted.page(params[:page]).per(50)
    if params[:search]
        @people = Person.search(params[:search]).sanjose.sorted.page(params[:page]).per(50)
      else
        @people = Person.where(:people_status => "active").sanjose.sorted.page(params[:page]).per(50)
      end

  end

  def show
    @person = Person.find(params[:id])
    @checks = CheckIn.where(:checkin_person =>@person.pco_id)
    @donations = Donation.where(:pco_id => @person.pco_id)
    pid = @person[:pco_id]

    @checkincal = checkin_grid(pid)
    @donationcal = donation_grid(pid)


    data_table_checkin = GoogleVisualr::DataTable.new
        data_table_checkin.new_column('date'  , 'Date')
        data_table_checkin.new_column('number', 'Vol/Att')
        data_table_checkin.add_rows(@checkincal)
    data_table_donation = GoogleVisualr::DataTable.new
        data_table_donation.new_column('date'  , 'Date')
        data_table_donation.new_column('number', 'Vol/Att')
        data_table_donation.add_rows(@donationcal)

        opts   = { :title => "Check-Ins", :width => 800, :height => 300, tooltip: { isHtml: FALSE }, calendar: { cellSize: 13.5 } }
        @chart_checkin = GoogleVisualr::Interactive::Calendar.new(data_table_checkin, opts)

        opts   = { :title => "Donations", :width => 800, :height => 300, tooltip: { isHtml: FALSE }, calendar: { cellSize: 13.5 } }
        @chart_donation = GoogleVisualr::Interactive::Calendar.new(data_table_donation, opts)
=begin
        opts   = { :title => "Volunteering", :width => 800, :height => 300, calendar: { cellSize: 13.5 } }
        @chart3 = GoogleVisualr::Interactive::Calendar.new(data_table, opts)
=end
  end

  def new
    @person = Person.new({:first_name => 'Default', :last_name => 'User'})
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      flash[:notice] = "Person created successfully"
      redirect_to(people_path)
    else
      render('new')
    end
  end

  def edit
    @person = Person.find(params[:id])

  end

  def update
    @person = Person.find(params[:id])

    if @person.update_attributes(person_params)
      flash[:notice] = "Person updated successfully"
      redirect_to(person_path(@person))
    else
      render('edit')
    end

  end

  def delete
    @person = Person.find(params[:id])
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    flash[:notice] = "Person #{@person.last_name} deleted successfully"
    redirect_to(people_path)
  end



private

  def person_params
    params.require(:person).permit(:pco_id, :first_name, :last_name, :email)
  end

end

app/views/admin/people/_checkinheader.html.erb
  <span style="background: darkseagreen;">______</span><span style="background: #fff;"> = Volunteered</span><span style="background: cornflowerblue;margin-left:20px;">______</span><span style="background: #fff;"> = Attended</span>
</br></br>

app/views/admin/people/_donationheader.html.erb
<span style="background: #BDB66F;">______</span><span style="background: #fff;"> = Donation > $0.00      </span><span style="background: #8C8540;">______</span><span style="background: #fff;">  = Donation > $1000      </span><span style="background: #464320;">______</span><span style="background: #fff;">  = Donation > $1M</span>

</br></br>

app/views/admin/people/_donationindex.html.erb
<% @page_title = "All People" %>

  <span style="background: darkkhaki;">______</span><span style="background: #fff;"> = Donation > $0.00</span>

  <table class="checkin_grid" summary="Person list">
  <% @calendar,lastsunday = get_calendar() %>
   <tr class="checkin_grid">
     <th style="width: 100px;">PCO ID</th>
     <th style="width: 250px;">Name</th>
     <th class="checkin_grid_dates"><%= (lastsunday.to_date - 119).strftime("%m/%d") %></th>
     <th class="checkin_grid_dates"><%= (lastsunday.to_date - 112).strftime("%m/%d") %></th>
     <th class="checkin_grid_dates"><%= (lastsunday.to_date - 105).strftime("%m/%d") %></th>
     <th class="checkin_grid_dates"><%= (lastsunday.to_date - 98).strftime("%m/%d") %></th>
     <th class="checkin_grid_dates"><%= (lastsunday.to_date - 91).strftime("%m/%d") %></th>
     <th class="checkin_grid_dates"><%= (lastsunday.to_date - 84).strftime("%m/%d") %></th>
     <th class="checkin_grid_dates"><%= (lastsunday.to_date - 77).strftime("%m/%d") %></th>
     <th class="checkin_grid_dates"><%= (lastsunday.to_date - 70).strftime("%m/%d") %></th>
     <th class="checkin_grid_dates"><%= (lastsunday.to_date - 63).strftime("%m/%d") %></th>
     <th class="checkin_grid_dates"><%= (lastsunday.to_date - 56).strftime("%m/%d") %></th>
     <th class="checkin_grid_dates"><%= (lastsunday.to_date - 49).strftime("%m/%d") %></th>
     <th class="checkin_grid_dates"><%= (lastsunday.to_date - 42).strftime("%m/%d") %></th>
     <th class="checkin_grid_dates"><%= (lastsunday.to_date - 35).strftime("%m/%d") %></th>
     <th class="checkin_grid_dates"><%= (lastsunday.to_date - 28).strftime("%m/%d") %></th>
     <th class="checkin_grid_dates"><%= (lastsunday.to_date - 21).strftime("%m/%d") %></th>
     <th class="checkin_grid_dates"><%= (lastsunday.to_date - 14).strftime("%m/%d") %></th>
     <th class="checkin_grid_dates"><%= (lastsunday.to_date - 7).strftime("%m/%d") %></th>
     <th class="checkin_grid_dates"><%= (lastsunday.to_date - 0).strftime("%m/%d") %></th>
   </tr>
   <% @people.each do |person|%>
   <% @calendar,lastsunday = get_calendar() %>
   <% stuff_donations(person.pco_id,@calendar) %>
   <tr>
     <td><%=  link_to person.pco_id, person.peopleapp_link %></td>
     <td><%= link_to(person.first_name + " " + person.last_name, admin_person_path(person), :class => 'action show') %></td>
     <td class="checkin_grid_dates"><%= dcolor_status(@calendar[(lastsunday.to_date - 119).strftime("%Y%m%d")][:amount])%></td>
     <td class="checkin_grid_dates"><%= dcolor_status(@calendar[(lastsunday.to_date - 112).strftime("%Y%m%d")][:amount])%></td>
     <td class="checkin_grid_dates"><%= dcolor_status(@calendar[(lastsunday.to_date - 105).strftime("%Y%m%d")][:amount])%></td>
     <td class="checkin_grid_dates"><%= dcolor_status(@calendar[(lastsunday.to_date - 98).strftime("%Y%m%d")][:amount])%></td>
     <td class="checkin_grid_dates"><%= dcolor_status(@calendar[(lastsunday.to_date - 91).strftime("%Y%m%d")][:amount])%></td>
     <td class="checkin_grid_dates"><%= dcolor_status(@calendar[(lastsunday.to_date - 84).strftime("%Y%m%d")][:amount])%></td>
     <td class="checkin_grid_dates"><%= dcolor_status(@calendar[(lastsunday.to_date - 77).strftime("%Y%m%d")][:amount])%></td>
     <td class="checkin_grid_dates"><%= dcolor_status(@calendar[(lastsunday.to_date - 70).strftime("%Y%m%d")][:amount])%></td>
     <td class="checkin_grid_dates"><%= dcolor_status(@calendar[(lastsunday.to_date - 63).strftime("%Y%m%d")][:amount])%></td>
     <td class="checkin_grid_dates"><%= dcolor_status(@calendar[(lastsunday.to_date - 56).strftime("%Y%m%d")][:amount])%></td>
     <td class="checkin_grid_dates"><%= dcolor_status(@calendar[(lastsunday.to_date - 49).strftime("%Y%m%d")][:amount])%></td>
     <td class="checkin_grid_dates"><%= dcolor_status(@calendar[(lastsunday.to_date - 42).strftime("%Y%m%d")][:amount])%></td>
     <td class="checkin_grid_dates"><%= dcolor_status(@calendar[(lastsunday.to_date - 35).strftime("%Y%m%d")][:amount])%></td>
     <td class="checkin_grid_dates"><%= dcolor_status(@calendar[(lastsunday.to_date - 28).strftime("%Y%m%d")][:amount])%></td>
     <td class="checkin_grid_dates"><%= dcolor_status(@calendar[(lastsunday.to_date - 21).strftime("%Y%m%d")][:amount])%></td>
     <td class="checkin_grid_dates"><%= dcolor_status(@calendar[(lastsunday.to_date - 14).strftime("%Y%m%d")][:amount])%></td>
     <td class="checkin_grid_dates"><%= dcolor_status(@calendar[(lastsunday.to_date - 7).strftime("%Y%m%d")][:amount])%></td>
     <td class="checkin_grid_dates"><%= dcolor_status(@calendar[(lastsunday.to_date - 0).strftime("%Y%m%d")][:amount])%></td>
   </tr>
   <% end%>
</table>

app/views/admin/people/_peopleindex.html.erb
<% @page_title = "All People" %>

  <span style="background: darkseagreen;">______</span><span style="background: #fff;"> = Volunteered</span><span style="background: cornflowerblue;margin-left:20px;">______</span><span style="background: #fff;"> = Attended</span>

      <table class="checkin_grid" summary="Person list">
        <% pcheck = Personcheckin.first %>
         <tr>
           <th class="checkin_grid_ids">PCO ID</th>
           <th class="checkin_grid_names">Name</th>
           <th class="checkin_grid_dates"><%= pcheck.week1 %></th>
           <th class="checkin_grid_dates"><%= pcheck.week2 %></th>
           <th class="checkin_grid_dates"><%= pcheck.week3 %></th>
           <th class="checkin_grid_dates"><%= pcheck.week4 %></th>
           <th class="checkin_grid_dates"><%= pcheck.week5 %></th>
           <th class="checkin_grid_dates"><%= pcheck.week6 %></th>
           <th class="checkin_grid_dates"><%= pcheck.week7 %></th>
           <th class="checkin_grid_dates"><%= pcheck.week8 %></th>
           <th class="checkin_grid_dates"><%= pcheck.week9 %></th>
           <th class="checkin_grid_dates"><%= pcheck.week10 %></th>
           <th class="checkin_grid_dates"><%= pcheck.week11 %></th>
           <th class="checkin_grid_dates"><%= pcheck.week12 %></th>
           <th class="checkin_grid_dates"><%= pcheck.week13 %></th>
           <th class="checkin_grid_dates"><%= pcheck.week14 %></th>
           <th class="checkin_grid_dates"><%= pcheck.week15 %></th>
           <th class="checkin_grid_dates"><%= pcheck.week16 %></th>
           <th class="checkin_grid_dates"><%= pcheck.week17 %></th>
           <th class="checkin_grid_dates"><%= pcheck.week18 %></th>
         </tr>
         <% @people.all.each do |person|%>
         <% pcheck = Personcheckin.where(:person_id => person.id )[0]%>
         <tr>
           <td  class="checkin_grid_ids"><%=  link_to person.pco_id, person.peopleapp_link %></td>
           <td  class="checkin_grid_names"><%= link_to(person.fullname, admin_person_path(person), :class => 'action show') %></td>
            <td class="checkin_grid_dates"><%= ccolor_status(pcheck.week1value)%></td>
            <td class="checkin_grid_dates"><%= ccolor_status(pcheck.week2value)%></td>
            <td class="checkin_grid_dates"><%= ccolor_status(pcheck.week3value)%></td>
            <td class="checkin_grid_dates"><%= ccolor_status(pcheck.week4value)%></td>
            <td class="checkin_grid_dates"><%= ccolor_status(pcheck.week5value)%></td>
            <td class="checkin_grid_dates"><%= ccolor_status(pcheck.week6value)%></td>
            <td class="checkin_grid_dates"><%= ccolor_status(pcheck.week7value)%></td>
            <td class="checkin_grid_dates"><%= ccolor_status(pcheck.week8value)%></td>
            <td class="checkin_grid_dates"><%= ccolor_status(pcheck.week9value)%></td>
            <td class="checkin_grid_dates"><%= ccolor_status(pcheck.week10value)%></td>
            <td class="checkin_grid_dates"><%= ccolor_status(pcheck.week11value)%></td>
            <td class="checkin_grid_dates"><%= ccolor_status(pcheck.week12value)%></td>
            <td class="checkin_grid_dates"><%= ccolor_status(pcheck.week13value)%></td>
            <td class="checkin_grid_dates"><%= ccolor_status(pcheck.week14value)%></td>
            <td class="checkin_grid_dates"><%= ccolor_status(pcheck.week15value)%></td>
            <td class="checkin_grid_dates"><%= ccolor_status(pcheck.week16value)%></td>
            <td class="checkin_grid_dates"><%= ccolor_status(pcheck.week17value)%></td>
            <td class="checkin_grid_dates"><%= ccolor_status(pcheck.week18value)%></td>
         </tr>
         <% end%>
      </table>